version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/strapi
permissions:
  - object: /tmp/
    owner: root
    group: root
    mode: 755
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 30
      runas: root