version: 0.2
    
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - npm install
      - npm install yarn -g
  build:
    commands:
      - NODE_ENV=production yarn build

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - 'node_modules/**/*'