version: 0.2
    
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre-build:
    commands:
      - npm install
      - npm install yarn -g
  build:
    commands:
      - NODE_ENV=production yarn build

artifacts:
  files:
    - appspec.yml
    - server.js
    - scripts/start.sh

cache:
  paths:
    - 'node_modules/**/*'