version: 0.2
    
phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - npm install yarn -g
      - npm install
      - NODE_ENV=production yarn build
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'